language: python
python:
  - 2.7
  - 3.6
sudo: required
install:
  - pip install -r requirements-doc.txt
script:
  - sudo pip install .
  - python -c "import check_mk_web_api"
  - cd doc
  - pydocmd build
  - cd ..
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: doc/_build/site
 on:
   branch: master
